import {useEffect,useRef} from 'react';

export type CrowdMember={name:string;image:string;facing?:1|-1};
type Walker={image:HTMLImageElement;sx?:number;sy?:number;sw?:number;sh?:number;x:number;y:number;width:number;height:number;speed:number;direction:1|-1;facing:1|-1;phase:number;teamIndex?:number;pauseUntil:number;lift:number;renderX:number;renderY:number;renderScaleX:number;free?:boolean};
type AlphaMask={data:Uint8ClampedArray;width:number;height:number};

const range=(min:number,max:number)=>min+Math.random()*(max-min);

export default function CrowdCanvas({members,onActive}:{members:CrowdMember[];onActive:(index:number|null)=>void}){
 const canvasRef=useRef<HTMLCanvasElement>(null);
 const activeRef=useRef<number|null>(null);
 useEffect(()=>{
  const canvas=canvasRef.current;if(!canvas)return;
  const context=canvas.getContext('2d');if(!context)return;
  const compact=matchMedia('(max-width: 767px), (pointer: coarse)').matches;
  let frame=0,visible=true,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,last=performance.now(),lastPaint=0;
  let width=0,height=0,walkers:Walker[]=[],teams:Walker[]=[],dragging:{walker:Walker;offsetX:number;offsetY:number}|null=null;
  const alphaMasks=new Map<HTMLImageElement,AlphaMask>();
  const sprite=new Image();sprite.src='/assets/team-crowd.png';
  const teamImages=members.map(member=>{const image=new Image();image.src=member.image;return image});
  const ready=[sprite,...teamImages].map(image=>new Promise<void>((resolve,reject)=>{if(image.complete&&image.naturalWidth)resolve();else{image.onload=()=>resolve();image.onerror=reject}}));

  const resetCrowd=(walker:Walker,initial=false)=>{walker.direction=Math.random()>.5?1:-1;walker.x=initial?range(-walker.width,width):walker.direction===1?-walker.width:width+walker.width;walker.y=height-walker.height+(compact?range(-34,22):range(25,155)-range(0,190));walker.speed=compact?range(22,48):range(42,118);walker.phase=range(0,Math.PI*2)};
  const resize=()=>{const rect=canvas.getBoundingClientRect();width=rect.width;height=rect.height;const dpr=Math.min(devicePixelRatio||1,compact?1.35:2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);context.setTransform(dpr,0,0,dpr,0,0);
   const narrow=width<500,cellW=sprite.naturalWidth/15,cellH=sprite.naturalHeight/7,crowdCount=narrow?24:compact?48:105;walkers=Array.from({length:crowdCount},(_,index)=>{const spriteIndex=(index*11)%105,scale=narrow?range(68/cellH,94/cellH):compact?range(100/cellH,158/cellH):range(.68,1.12),walker:Walker={image:sprite,sx:(spriteIndex%15)*cellW,sy:Math.floor(spriteIndex/15)*cellH,sw:cellW,sh:cellH,x:0,y:0,width:cellW*scale,height:cellH*scale,speed:0,direction:1,facing:1,phase:0,pauseUntil:0,lift:0,renderX:0,renderY:0,renderScaleX:1};resetCrowd(walker,true);return walker});
   teams=teamImages.map((image,index)=>{const targetH=narrow?112:compact?range(132,168):range(cellH*1.5,cellH*1.85);const ratio=image.naturalWidth/image.naturalHeight,targetW=targetH*ratio,lane=width/members.length;const walker:Walker={image,x:narrow?index*lane+Math.max(0,(lane-targetW)/2):compact?Math.max(0,((index+.5)/members.length)*width-targetW/2):range(0,width),y:height-targetH+(narrow?range(0,18):compact?range(18,48):range(75,155)),width:targetW,height:targetH,speed:narrow?range(8,15):compact?range(25,42):range(48,78),direction:index%2? -1:1,facing:members[index].facing??1,phase:index*1.4,pauseUntil:0,teamIndex:index,lift:0,renderX:0,renderY:0,renderScaleX:1};return walker});
  };
  const drawWalker=(walker:Walker,time:number)=>{const bob=Math.sin(time*.012+walker.phase)*5,scaleX=walker.direction*walker.facing,liftY=walker.lift*58;walker.renderX=walker.x;walker.renderY=walker.y+bob-liftY;walker.renderScaleX=scaleX;context.save();context.translate(walker.x+(scaleX<0?walker.width:0),walker.renderY);context.scale(scaleX,1);
   if(walker.sx!==undefined)context.drawImage(walker.image,walker.sx,walker.sy!,walker.sw!,walker.sh!,0,0,walker.width,walker.height);else context.drawImage(walker.image,0,0,walker.width,walker.height);context.restore();
   if(walker.teamIndex!==undefined){const narrow=width<500,x=walker.x+walker.width*.5,y=walker.renderY+3;context.fillStyle='#0a0b0a';if(narrow){context.fillRect(x-7,y,14,14);context.fillStyle='#f4f3ef';context.beginPath();context.arc(x,y+7,3,0,Math.PI*2);context.fill()}else{const label=`●  ${members[walker.teamIndex].name.toUpperCase()}`;context.font='600 9px Arial';const labelW=Math.ceil(context.measureText(label).width)+20;context.fillRect(x-labelW/2,y,labelW,24);context.fillStyle='#f4f3ef';context.textAlign='center';context.textBaseline='middle';context.fillText(label,x,y+12)}}};
  const render=(now:number)=>{if(!visible||compact&&now-lastPaint<32){frame=requestAnimationFrame(render);return}lastPaint=now;const dt=Math.min((now-last)/1000,.035);last=now;context.clearRect(0,0,width,height);if(!reduced){walkers.forEach(walker=>{walker.x+=walker.speed*walker.direction*dt;if(walker.direction===1&&walker.x>width+walker.width||walker.direction===-1&&walker.x<-walker.width)resetCrowd(walker) });teams.forEach(walker=>{const selected=walker.teamIndex===activeRef.current,isDragging=dragging?.walker===walker;walker.lift+=(Number(selected&&!isDragging)-walker.lift)*Math.min(1,dt*10);if(selected||now<walker.pauseUntil)return;walker.x+=walker.speed*walker.direction*dt;const lane=width/members.length,narrow=width<500&&!walker.free,left=narrow?walker.teamIndex!*lane:0,right=narrow?(walker.teamIndex!+1)*lane-walker.width:width-walker.width*.55;if(walker.direction===1&&walker.x>right){walker.x=right;walker.direction=-1;walker.pauseUntil=now+260}else if(walker.direction===-1&&walker.x<(narrow?left:-walker.width*.45)){walker.x=narrow?left:-walker.width*.45;walker.direction=1;walker.pauseUntil=now+260}})}
   [...walkers,...teams].sort((a,b)=>{const aSelected=a.teamIndex===activeRef.current,bSelected=b.teamIndex===activeRef.current;if(aSelected!==bSelected)return aSelected?1:-1;const aTeam=a.teamIndex!==undefined,bTeam=b.teamIndex!==undefined;if(aTeam!==bTeam)return aTeam?1:-1;return(a.y+a.height)-(b.y+b.height)}).forEach(walker=>drawWalker(walker,now));frame=requestAnimationFrame(render)};
  const point=(event:PointerEvent)=>{const rect=canvas.getBoundingClientRect();return{x:event.clientX-rect.left,y:event.clientY-rect.top}};
  const findTeam=(x:number,y:number)=>{for(let i=teams.length-1;i>=0;i--){const person=teams[i],localY=(y-person.renderY)/person.height;if(localY<0||localY>1)continue;let localX=(x-person.renderX)/person.width;if(person.renderScaleX<0)localX=1-localX;if(localX<0||localX>1)continue;const mask=alphaMasks.get(person.image);if(!mask)return person;const px=Math.round(localX*(mask.width-1)),py=Math.round(localY*(mask.height-1));for(let oy=-2;oy<=2;oy++)for(let ox=-2;ox<=2;ox++){const sx=Math.max(0,Math.min(mask.width-1,px+ox)),sy=Math.max(0,Math.min(mask.height-1,py+oy));if(mask.data[(sy*mask.width+sx)*4+3]>28)return person}}return null};
  const locateProfile=(person:Walker)=>{const host=canvas.parentElement;if(!host)return;host.style.setProperty('--focus-x',`${Math.max(210,Math.min(width-210,person.x+person.width*.5))}px`);host.style.setProperty('--focus-y',`${Math.max(205,person.y-person.lift*58)}px`)};
  const pointer=(event:PointerEvent)=>{const{x,y}=point(event);if(dragging){dragging.walker.x=Math.max(-dragging.walker.width*.35,Math.min(width-dragging.walker.width*.65,x-dragging.offsetX));dragging.walker.y=Math.max(10,Math.min(height-dragging.walker.height*.35,y-dragging.offsetY));locateProfile(dragging.walker);canvas.style.cursor='pointer';return}const person=findTeam(x,y),hit=person?.teamIndex??null;if(person)locateProfile(person);if(hit!==activeRef.current){activeRef.current=hit;onActive(hit)}canvas.style.cursor=hit===null?'default':'pointer'};
  const pointerDown=(event:PointerEvent)=>{const{x,y}=point(event),person=findTeam(x,y);if(!person)return;event.preventDefault();person.y=person.renderY;person.lift=0;person.phase=-performance.now()*.012;dragging={walker:person,offsetX:x-person.x,offsetY:y-person.y};activeRef.current=person.teamIndex!;onActive(person.teamIndex!);locateProfile(person);canvas.setPointerCapture(event.pointerId);canvas.style.cursor='pointer'};
  const pointerUp=(event:PointerEvent)=>{if(!dragging)return;dragging.walker.free=true;dragging=null;if(canvas.hasPointerCapture(event.pointerId))canvas.releasePointerCapture(event.pointerId);const{x,y}=point(event),person=findTeam(x,y),hit=person?.teamIndex??null;activeRef.current=hit;onActive(hit);canvas.style.cursor=hit===null?'default':'pointer'};
  const leave=()=>{if(dragging)return;activeRef.current=null;onActive(null);canvas.style.cursor='default'};
  const observer=new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting??true},{rootMargin:'120px'});observer.observe(canvas);
  Promise.all(ready).then(()=>{teamImages.forEach(image=>{const maskHeight=256,maskWidth=Math.max(1,Math.round(maskHeight*image.naturalWidth/image.naturalHeight)),maskCanvas=document.createElement('canvas');maskCanvas.width=maskWidth;maskCanvas.height=maskHeight;const maskContext=maskCanvas.getContext('2d',{willReadFrequently:true});if(!maskContext)return;maskContext.drawImage(image,0,0,maskWidth,maskHeight);alphaMasks.set(image,{data:maskContext.getImageData(0,0,maskWidth,maskHeight).data,width:maskWidth,height:maskHeight})});resize();frame=requestAnimationFrame(render)}).catch(()=>{});
  canvas.addEventListener('pointermove',pointer);canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('pointerleave',leave);window.addEventListener('resize',resize);
  return()=>{cancelAnimationFrame(frame);observer.disconnect();canvas.removeEventListener('pointermove',pointer);canvas.removeEventListener('pointerdown',pointerDown);canvas.removeEventListener('pointerup',pointerUp);canvas.removeEventListener('pointercancel',pointerUp);canvas.removeEventListener('pointerleave',leave);window.removeEventListener('resize',resize)};
 },[members,onActive]);
 return <canvas ref={canvasRef} className="team-canvas" data-cursor="drag" aria-label="Multitud en movimiento. Las cinco personas del equipo FRACTO se pueden arrastrar y reubicar"/>;
}
